# Generated by Django 3.1.5 on 2021-01-26 20:33

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0006_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField(default=django.utils.timezone.now)),
                ('endTime', models.DateField()),
                ('size', models.CharField(choices=[('5v5', '5v5'), ('7v7', '7v7'), ('12v12', '12v12')], default='5v5', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='turf_list',
            name='id',
        ),
        migrations.AddField(
            model_name='turf_list',
            name='turf_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turf_list',
            name='num_12v12',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='turf_list',
            name='num_5v5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='turf_list',
            name='num_7v7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='turf_list',
            name='num_7v7_5v5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1),
        ),
    ]
