# Generated by Django 3.1.5 on 2021-01-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0010_auto_20210128_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf_list',
            old_name='username',
            new_name='userid',
        ),
    ]
