# Generated by Django 3.1.5 on 2021-01-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0012_auto_20210128_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_list',
            name='userid',
        ),
    ]
