# Generated by Django 3.1.5 on 2021-01-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0014_turf_list_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_list',
            name='owner',
        ),
    ]
