# Generated by Django 3.1.5 on 2021-01-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0018_auto_20210130_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_list',
            name='price_per_hour_5v5',
        ),
    ]
