# Generated by Django 3.1.5 on 2021-02-12 16:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turf', '0023_auto_20210131_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='endTime',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_of_hours',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, verbose_name='Number Of Hours'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_5v5_requested', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1, verbose_name='Number Of Turfs')),
                ('hours', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, verbose_name='Number Of Hours')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('startTime', models.TimeField(blank=True, verbose_name='Start Time')),
                ('num_5v5_turfs_total', models.IntegerField(default=1)),
                ('booked_turf_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.turf_list')),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
