# Generated by Django 3.1.5 on 2021-02-12 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0024_auto_20210212_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_of_hours',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guest',
            new_name='username',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startTime',
            field=models.TimeField(blank=True, verbose_name='Start Time'),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
