# Generated by Django 3.1 on 2021-01-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(default='', upload_to='../media')),
                ('facilities', models.CharField(default='', max_length=500)),
                ('near_by_turf', models.CharField(default='', max_length=500)),
                ('emergency', models.CharField(default='', max_length=500)),
                ('events', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
