# Generated by Django 3.1.5 on 2021-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_list',
            name='num_12v12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turf_list',
            name='num_5v5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turf_list',
            name='num_7v7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turf_list',
            name='num_7v7_5v5',
            field=models.IntegerField(default=0),
        ),
    ]
