# Generated by Django 3.1.5 on 2021-01-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_auto_20210126_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_list',
            name='near_by_turf',
        ),
        migrations.AddField(
            model_name='turf_list',
            name='price_per_hour_12v12',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='turf_list',
            name='price_per_hour_5v5',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='turf_list',
            name='price_per_hour_7v7',
            field=models.IntegerField(default=700),
        ),
    ]
