# Generated by Django 3.1.5 on 2021-01-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='{{username}}', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('emailid', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
