# Generated by Django 3.1.5 on 2021-01-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0005_auto_20210127_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
