# Generated by Django 3.1 on 2021-01-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0016_turf_list_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='../media')),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
