# Generated by Django 3.1.5 on 2021-01-29 19:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turf', '0017_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='size',
        ),
        migrations.RemoveField(
            model_name='turf_list',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='turf_list',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='turf_list',
            name='num_12v12',
        ),
        migrations.RemoveField(
            model_name='turf_list',
            name='num_5v5',
        ),
        migrations.RemoveField(
            model_name='turf_list',
            name='num_7v7',
        ),
        migrations.RemoveField(
            model_name='turf_list',
            name='num_7v7_5v5',
        ),
        migrations.RemoveField(
            model_name='turf_list',
            name='price_per_hour_12v12',
        ),
        migrations.RemoveField(
            model_name='turf_list',
            name='price_per_hour_7v7',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_5v5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='turf_list',
            name='has_first_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turf_list',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turf_list',
            name='has_refreshments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turf_list',
            name='num_5v5_turfs',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='endTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
