# Generated by Django 3.1.5 on 2021-01-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0020_auto_20210131_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_list',
            name='weekdends_turf_opening_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
