# Generated by Django 3.1.5 on 2021-01-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0021_turf_list_weekdends_turf_opening_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf_list',
            old_name='weekdends_turf_opening_time',
            new_name='weekends_turf_opening_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_turf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.turf_list'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_5v5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='turf_list',
            name='num_5v5_turfs',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1),
        ),
    ]
