# Generated by Django 3.1.5 on 2021-02-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0025_auto_20210212_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='startTime',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
